clang shell.c -o shell
clang ls_command.c -o ls_command
clang cat_command.c -o cat_command
clang date_command.c -o date_command
clang mkdir_command.c -o mkdir_command
clang rm_command.c -o rm_command
./shell